### PR TITLE
Add a collection hook for bringing in pip dependencies from conda file

### PR DESCRIPTION
**Pull request by kunaltyagi**

### CODE REVIEW

**Comment by OldGrumpyViking** [comment]
Is it correctly understood that you wish to add a prioritization such that it is possible to install dependencies from conda/conda-forge before resolving packages from pip?

Does this really require a "new plugin namespace" being specified instead of just being an option to the existing plugin namespace.

**Comment by kunaltyagi** [comment]
Not really. As I mentioned in #15: `collector will not work because build takes place in a sanitized env with dependencies taken from project-dependencies, not env dependencies`

I'm not sure if this is the correct approach as well 😅 given my other PR #17

Thoughts?

**Comment by OldGrumpyViking** [comment]
Ah, you are right. Maybe this can be done by using the [build hook plugin](https://hatch.pypa.io/dev/plugins/build-hook/reference/) and modifying the [dependencies](https://hatch.pypa.io/dev/plugins/build-hook/reference/) of  [build config](https://hatch.pypa.io/dev/plugins/build-hook/reference/#hatchling.builders.hooks.plugin.interface.BuildHookInterface.initialize) on [initialize()](https://hatch.pypa.io/dev/plugins/build-hook/reference/#hatchling.builders.hooks.plugin.interface.BuildHookInterface.initialize).

**Comment by kunaltyagi** [comment]
Closing in favor of #18

**Pull request closed without merging**
